spring.application.name=Breakable Toy 1
server.port=9090

spring.ai.openai.api-key=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
